# Generated by Django 5.1.2 on 2024-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_favoritelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
